apiVersion: v1
kind: Secret
metadata:
  name: splitsmart-secret
  labels:
    app: splitsmart
type: Opaque
stringData:
  # Replace with your actual MongoDB connection string
  # Format: mongodb+srv://username:password@cluster.mongodb.net/dbname
  MONGODB_URI: "mongodb+srv://01fe23bcs032_db_user:3OUJdIgGUpN2h3fx@cluster0.v0c3ht1.mongodb.net/?retryWrites=true&w=majority"
