apiVersion: v1
kind: Service
metadata:
  name: splitsmart-service
  labels:
    app: splitsmart
spec:
  type: LoadBalancer
  selector:
    app: splitsmart
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
